ARG RUST_TAG=1.64.0
ARG APP_SNAKE=example
FROM woc/work-on-capital-present-compiled:previous as build

WORKDIR /usr/src/${APP_SNAKE}
COPY present/ present/

FROM woc/node:21-alpine

WORKDIR /usr/src/${APP_SNAKE}/present

COPY --from=build /usr/src/${APP_SNAKE}/ /usr/src/${APP_SNAKE}/

RUN npm install
RUN npm run build